---
title: "Direct Comparison in endemic scenario"
output:
  pdf_document: default
  html_notebook: default
---

# Direct comparison

```{r}
rm(list = ls())
library(ggplot2)
library(plyr)
library(dplyr)
library(reshape2)
library(viridis)
source("../analysis/logfile/summary_data_from_BEAST_log.R")
case= 45
bdInfDir="../data/summary_data/bdpsi/BD_rhoSamp/"
scInfDir="../data/summary_data/sc_inf/BD_rhoSamp/"
picPath = "../analysis/directComparison/epidemic_case/plots/"
```

```{r}
bdResult = load(paste0(bdInfDir, "all_params_", case, ".Rdat"))
bdResult = get(bdResult)
bdInfResult = bdResult[[2]][which(bdResult[[2]][1,] != 0.0), ]
bdInfResult = bdResult[[2]][which(bdResult[[2]][,1] != 0.0), ]
scResult = load(paste0(scInfDir, "all_params_", case, ".Rdat"))
scResult = get(scResult)
scInfResult = scResult[[2]][which(scResult[[2]][,1] != 0.0), ]
simParams = as.numeric(scResult[[1]])
rm(result_45)
```

```{r}
b_melted  = melt(bdInfResult[,c(7,10,31)], id.vars="seed" )
b_upper_melted = melt(bdInfResult[,c(9,12,31)], id.vars="seed" )
b_lower_melted = melt(bdInfResult[,c(8,11,31)], id.vars="seed" )
colnames(b_upper_melted) <- c("seed", "var_upper", "val_upper")
colnames(b_lower_melted) <- c("seed", "var_lower", "val_lower")

s_melted  = melt(scInfResult[,c(28,31,34)], id.vars="seed" )
s_upper_melted = melt(scInfResult[,c(30,33,34)], id.vars="seed" )
s_lower_melted = melt(scInfResult[,c(29,32,34)], id.vars="seed" )
colnames(s_upper_melted) <- c("seed", "var_upper", "val_upper")
colnames(s_lower_melted) <- c("seed", "var_lower", "val_lower")

bdat = cbind(b_melted, b_lower_melted[, c(2,3)], b_upper_melted[, c(2,3)])
bdat$variable = as.character(bdat$variable)
bdat$var_lower = as.character(bdat$var_lower)
bdat$var_upper = as.character(bdat$var_upper)

bdat$variable = as.factor(bdat$variable)
bdat$var_lower = as.factor(bdat$var_lower)
bdat$var_upper = as.factor(bdat$var_upper)
bdat$Model = "MBD"

sdat = cbind(s_melted, s_lower_melted[, c(2,3)], s_upper_melted[, c(2,3)])
sdat$Model = "SC"

dat = rbind(sdat, bdat)
dat$seed = as.numeric(dat$seed)

# order by mr01
subdat = dat[which(dat$variable == "mr01" & dat$Model == "SC"), ]
subdat = subdat[order(subdat$value), ]
subdat$orderedSeed = 1:nrow(subdat)

mapping = data.frame(ind=subdat$orderedSeed, seed=subdat$seed)
dat$orderedSeed = NA
for (i in 1:length(dat$orderedSeed)){
    if (length(mapping[which(mapping$seed == dat[i, "seed"]), "ind"]) == 0 ){next()}
  dat[i, "orderedSeed"] = mapping[which(mapping$seed == dat[i, "seed"]), "ind"]
}
dat = dat[order(dat$orderedSeed),]
```


```{r}
# add prior
library(HDInterval)
set.seed(1)
oneOnX_sample_generator <- function(n=1, lbound, ubound){
  
  unif = runif(n = n,min = log(lbound), max = log(ubound) )
  oneOnXsample = exp(unif)

  # oneOnXsample = -1
  # # bound 1/x between [10e-3, 10e3]
  # while (oneOnXsample > 1000 | oneOnXsample < 0.001){
  #   # generate sample from unif distr
  #   unif_sample =runif(1)
  #   # transform to X ~ 1/X
  #   oneOnXsample = ubound**unif_sample * lbound**(1 - unif_sample)
  # }

 return(oneOnXsample)
}
# generate samples from the prior
q01_samples = rexp(n = 100000, rate = 1)  # backward migration 
N0_samples = oneOnX_sample_generator(lbound = 0.01, ubound = 100, n = 100000)
N1_samples = oneOnX_sample_generator(lbound = 0.01, ubound = 100, n = 100000)
N0_samples = replicate(oneOnX_sample_generator(lbound = 0.01, ubound = 100), n = 100000)
N1_samples = replicate(oneOnX_sample_generator(lbound = 0.01, ubound = 100), n = 100000)
mr10_samples = q01_samples * N0_samples /N1_samples # forward migration

med_sc = as.numeric(median(mr10_samples, na.rm = TRUE))
lower_sc = as.numeric(hdi(mr10_samples,credMass = 0.95)[[1]])
upper_sc = as.numeric(hdi(mr10_samples,credMass = 0.95)[[2]])

med_bd  = as.numeric(median(q01_samples, na.rm = TRUE))
lower_bd = as.numeric(hdi(q01_samples,credMass = 0.95)[[1]])
upper_bd = as.numeric(hdi(q01_samples,credMass = 0.95)[[2]])

dat[nrow(dat) + 1, ] = c(110, "mr10", med_bd, "mr10_lower", lower_bd, "mr10_upper", upper_bd, "MBD prior",110)
dat[nrow(dat) + 1, ] = c(115, "mr10", med_sc, "mr10_lower", lower_sc, "mr10_upper", upper_sc, "SC prior", 115)
dat[nrow(dat) + 1, ] = c(110, "mr01", med_bd, "mr01_lower", lower_bd, "mr01_upper", upper_bd, "MBD prior",110)
dat[nrow(dat) + 1, ] = c(115, "mr01", med_sc, "mr01_lower", lower_sc, "mr01_upper", upper_sc, "SC prior", 115)
#dat$Model = as.factor(dat$Model)
```

```{r}
library(latex2exp)
p <- ggplot(subset(dat, variable %in% "mr01"), aes(x=as.numeric(orderedSeed), y=log(as.numeric(value)), col = Model ))+
  geom_point() + 
  # geom_crossbar(aes(ymin=log(as.numeric(val_lower)), ymax=log(as.numeric(val_upper)), fill = Model),
  #               alpha=0.1, width=0.2) +
  geom_pointrange(aes(ymin=log(as.numeric(val_lower)), ymax=log(as.numeric(val_upper))), shape=21, fatten = -0.5, size = 1.0, alpha = 0.5 ) +
  
  geom_hline(yintercept = log(1.0), col="black") +
  xlab("Simulation Number") + 
  ylab(TeX("95% HPD interval of $m_{rb}$")) +  scale_color_manual(values = c(
    '#de77ae',
    '#8e0152',
    '#4d9221',
    '#00441b')) +
  theme_bw(base_family = "Times") + 
  theme(panel.grid.major.x  = element_blank(), panel.grid.minor.x = element_blank(), legend.title = element_blank())

tiff(filename = paste0(picPath, "case", case,"_inferredmr01.tiff"), width = 13, height = 10, units = "cm", compression = "none", family="Times", res = 300)
print(p)
dev.off()

pdf(file = paste0(picPath, "case", case,"_inferredmr01.pdf"), family = "Times")
print(p)
dev.off()
p
```

```{r}
dat = dat[1:(nrow(dat)-4),]
# order by q01
subdat = dat[which(dat$variable == "mr10" & dat$Model == "SC"), ]
subdat = subdat[order(as.numeric(subdat$value)), ]
subdat$orderedSeed = 1:nrow(subdat)

mapping = data.frame(ind=subdat$orderedSeed, seed=subdat$seed)
dat$orderedSeed = NA
for (i in 1:length(dat$orderedSeed)){
  if (length(mapping[which(mapping$seed == dat[i, "seed"]), "ind"]) == 0 ){next()}
  dat[i, "orderedSeed"] = mapping[which(mapping$seed == dat[i, "seed"]), "ind"]
}
dat = dat[order(dat$orderedSeed),]
dat[nrow(dat) + 1, ] = c(110, "mr10", med_bd, "mr10_lower", lower_bd, "mr10_upper", upper_bd, "MBD prior",110)
dat[nrow(dat) + 1, ] = c(115, "mr10", med_sc, "mr10_lower", lower_sc, "mr10_upper", upper_sc, "SC prior", 115)
dat[nrow(dat) + 1, ] = c(110, "mr01", med_bd, "mr01_lower", lower_bd, "mr01_upper", upper_bd, "MBD prior",110)
dat[nrow(dat) + 1, ] = c(115, "mr01", med_sc, "mr01_lower", lower_sc, "mr01_upper", upper_sc, "SC prior", 115)
```



```{r}
p <- ggplot(subset(dat, variable %in% "mr10"), aes(x=as.numeric(orderedSeed), y=log(as.numeric(value)), col = Model ))+
  geom_point() + 
  # geom_crossbar(aes(ymin=log(as.numeric(val_lower)), ymax=log(as.numeric(val_upper)), fill = Model),
  #               alpha=0.1, width=0.2) +
  geom_pointrange(aes(ymin=log(as.numeric(val_lower)), ymax=log(as.numeric(val_upper))), shape=21, fatten = .5, size = 1.8, alpha = 0.5 ) +
  
  geom_hline(yintercept = log(1.0), col="black") +
  xlab("Simulation Number") + 
  ylab(TeX("95% HPD interval of $m_{br}$")) +  scale_color_manual(values = c(
    '#de77ae',
    '#8e0152',
    '#4d9221',
    '#00441b')) +
  theme_bw(base_family = "Times") + 
  theme(panel.grid.major.x  = element_blank(), panel.grid.minor.x = element_blank(), legend.title = element_blank())

tiff(filename = paste0(picPath, "case", case,"_inferredmr10.tiff"), width = 1500, height = 1500, units = "px", compression = "none", family="Times", res = 300)
print(p)
dev.off()

pdf(file = paste0(picPath, "case", case,"_inferredmr10.pdf"), family = "Times")
print(p)
dev.off()
p
```

# Population size


#```{r}
b_melted  = melt(bdInfResult[,c(19,22,31)], id.vars="seed" )
b_upper_melted = melt(bdInfResult[,c(21,24,31)], id.vars="seed" )
b_lower_melted = melt(bdInfResult[,c(20,23,31)], id.vars="seed" )
colnames(b_upper_melted) <- c("seed", "var_upper", "val_upper")
colnames(b_lower_melted) <- c("seed", "var_lower", "val_lower")

s_melted  = melt(scInfResult[,c(1,4,34)], id.vars="seed" )
s_upper_melted = melt(scInfResult[,c(3,6,34)], id.vars="seed" )
s_lower_melted = melt(scInfResult[,c(2,5,34)], id.vars="seed" )
colnames(s_upper_melted) <- c("seed", "var_upper", "val_upper")
colnames(s_lower_melted) <- c("seed", "var_lower", "val_lower")

bdat = cbind(b_melted, b_lower_melted[, c(2,3)], b_upper_melted[, c(2,3)])

bdat$Model = "MBD"

sdat = cbind(s_melted, s_lower_melted[, c(2,3)], s_upper_melted[, c(2,3)])
sdat$Model = "SC"
#calculate cumulative population size over sampling period
sdat[, c(3,5,7)] = sdat[, c(3,5,7)] * 10

dat = rbind(sdat, bdat)
dat$seed = as.numeric(dat$seed)

# order by N0
subdat = dat[which(dat$variable == "N0" & dat$Model == "MBD"), ]
subdat = subdat[order(subdat$value), ]
subdat$orderedSeed = 1:nrow(subdat)

mapping = data.frame(ind=subdat$orderedSeed, seed=subdat$seed)
dat$orderedSeed = -1
for (i in 1:length(dat$orderedSeed)){
  dat[i, "orderedSeed"] = mapping[which(mapping$seed == dat[i, "seed"]), "ind"]
}
dat = dat[order(dat$orderedSeed),]
```

#```{r}
p <- ggplot(subset(dat, variable %in% "N0"), aes(x=orderedSeed, y=value, col = Model, )) +
  geom_point() + geom_errorbar(aes(ymin=val_lower, ymax=val_upper), alpha=0.4)  +
  theme_minimal() +
  geom_hline(yintercept = 10/simParams[2]) +
  xlab("Simulation Number") +
  ylab("cumulative population size N0") +ylim(0,5000)

#+ scale_color_manual( values = viridis(2))

pdf(file = paste0(picPath, "case45_inferredN0.pdf"))
print(p)
dev.off()

p
```
#```{r}
# order by N1
subdat = dat[which(dat$variable == "N1" & dat$Model == "SC"), ]
subdat = subdat[order(subdat$value), ]
subdat$orderedSeed = 1:nrow(subdat)

mapping = data.frame(ind=subdat$orderedSeed, seed=subdat$seed)
dat$orderedSeed = -1
for (i in 1:length(dat$orderedSeed)){
  dat[i, "orderedSeed"] = mapping[which(mapping$seed == dat[i, "seed"]), "ind"]
}
dat = dat[order(dat$orderedSeed),]
```


<!-- ```{r} -->
<!-- p <- ggplot(subset(dat, variable %in% "N1"), aes(x=orderedSeed, y=value, col = Model, )) + -->
<!--   geom_point() + geom_errorbar(aes(ymin=val_lower, ymax=val_upper), alpha=0.4)  + -->
<!--   theme_minimal() + -->
<!--   geom_hline(yintercept = 10/simParams[2]) + -->
<!--   xlab("Simulation Number") + -->
<!--   ylab("cumulative population size N1") +ylim(0,5000) -->

<!-- pdf(file = paste0(picPath, "case45_inferredN1.pdf")) -->
<!-- print(p) -->
<!-- dev.off() -->

<!-- #+ scale_color_manual( values = viridis(2)) -->
<!-- p -->
<!-- ``` -->